#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# check current branch is main branch
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "You can't commit directly to master/main branch"
  exit 1
fi

# check yarn is installed
if [ -z `which yarn` ]; then
  echo "yarn is not installed or not in your PATH!\nYou should install yarn or add it's path to your ~/.huskyrc"
  exit 1
fi

# lint & fix staged files
# yarn lint --fix
yarn lint-staged
